### PR TITLE
Page speed insights

### PR DESCRIPTION
**Pull request by SignpostMarv**
- removed some files that weren't referenced
- eslinted because reasons
- JS & CSS minified (CSS was a little tricky as the default cssnano set borked the design)
- refactored the JS to use the same async loader used for the twitter widget
- used Google's vulcanize tool to inline the css & js
- `grunt watch`'d everything to automate building the inlined version of the index page.

I didn't take the extra step of minifying the HTML, because bringing the speed/user experience scores into the green seemed to be "good enough".

### CODE REVIEW

**Comment by jehna** [comment]
@SignpostMarv is [this link](http://dev.signpostmarv.name/pub/verbalexpressions.github.io/) up-to-date with this PR?
If yes, there's a couple of easy points you could fetch :) These links seem to be too close to each other, they could have a bit more space around them on mobile:

screen shot 2016-02-04 at 09 31 06
screen shot 2016-02-04 at 09 33 36

**Comment by SignpostMarv** [comment]
@jehna yes the link is up-to-date with the PR; although I'm thinking if I do something similar in future, I should have multiple uploads to match with each commit.

48px minimum dimensions added as per [Size Tap Targets Appropriately](https://developers.google.com/speed/docs/insights/SizeTapTargetsAppropriately)

**Comment by SignpostMarv** [comment]
:D https://developers.google.com/speed/pagespeed/insights/?url=verbalexpressions.github.io

**Comment by SignpostMarv** [comment]
noticed an issue with line lengths, was considering patching it here, but thought of a different solution; will make a separate pull request.

**Comment by SignpostMarv** [comment]
have hit the API rate limit, will have to wait for it to reset :P

**Pull request merged**
